image:
  name: hashicorp/terraform:1.9.1
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  TF_ROOT: $CI_PROJECT_DIR

cache:
  key: $TF_ROOT
  paths:
    - $TF_ROOT/.terraform/
    - $TF_ROOT/.terraform.lock.hcl

stages:
  - test
  - predeploy
  - deploy

test:
  stage: test
  before_script:
    - cd $TF_ROOT
    - terraform init
  script:
    - terraform fmt -recursive -check
    - terraform validate

plan:
  only:
    refs:
      - master
  stage: predeploy
  before_script:
    - cd $TF_ROOT
  script:
    - terraform plan -var-file=$TFVARSFILE -out tfplan
  artifacts:
    name: tfplan
    expire_in: 1 week
    paths:
      - $TF_ROOT/tfplan

apply:
  when: manual
  only:
    refs:
      - master
  stage: deploy
  environment:
    name: production
  before_script:
    - cd $TF_ROOT
  script:
    - terraform apply -auto-approve -var-file=$TFVARSFILE
